//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_RequestForQuotationLinePrice
    {
        public int C_RequestForQuotationLinePrice_ID { get; set; }
        public Nullable<int> C_Size_ID { get; set; }
        public Nullable<int> C_Purpose_ID { get; set; }
        public Nullable<int> C_Bottle_Colour_ID { get; set; }
        public Nullable<int> C_Label_Colour_ID { get; set; }
        public Nullable<int> C_Image_ID { get; set; }
        public Nullable<int> C_Shape_ID { get; set; }
        public Nullable<int> C_Quotation_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
    
        public virtual C_Bottle_Colour C_Bottle_Colour { get; set; }
        public virtual C_Image C_Image { get; set; }
        public virtual C_Label_Colour C_Label_Colour { get; set; }
        public virtual C_Purpose C_Purpose { get; set; }
        public virtual C_Quotation C_Quotation { get; set; }
        public virtual C_Shape C_Shape { get; set; }
        public virtual C_Size C_Size { get; set; }
        public virtual Product Product { get; set; }
    }
}
