//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SupplierOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_SupplierOrder()
        {
            this.C_Supplier_OrderLines = new HashSet<C_Supplier_OrderLines>();
        }
    
        public int C_SupplierOrder_ID { get; set; }
        public string C_SupplierOrder_Quantity { get; set; }
        public string C_SupplierOrder_Address { get; set; }
        public string C_SupplierOrder_Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Supplier_OrderLines> C_Supplier_OrderLines { get; set; }
    }
}
