//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TrackOrder_Status
    {
        public int C_TrackOrder_Status_ID { get; set; }
    }
}
