//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_UserSecurity_Question
    {
        public int C_User_ID { get; set; }
        public string C_User_Name { get; set; }
        public string C_User_Surname { get; set; }
        public string C_User_UserName { get; set; }
        public string C_User_Password { get; set; }
        public Nullable<int> UserRole_ID { get; set; }
    
        public virtual UserRole UserRole { get; set; }
    }
}
