//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItem
    {
        public int CartItem_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> C_Product_Size_ID { get; set; }
    
        public virtual C_Product_Size C_Product_Size { get; set; }
    }
}
