//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientOrder()
        {
            this.Carts = new HashSet<Cart>();
            this.ClientOrderLines = new HashSet<ClientOrderLine>();
        }
    
        public int ClientOrder_ID { get; set; }
        public string ClientOrder_Date { get; set; }
        public string ClientOrder_Total { get; set; }
        public string ClientOrder_Items { get; set; }
        public Nullable<int> ClientOrder_TotalQuantity { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public Nullable<int> DeliveryCollection_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientOrderLine> ClientOrderLines { get; set; }
        public virtual DeliveryCollection DeliveryCollection { get; set; }
    }
}
