//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryAddress
    {
        public int DeliveryAddress_ID { get; set; }
        public string Street_Name { get; set; }
        public Nullable<int> Street_Number { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public Nullable<int> Surburb_ID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Surburb Surburb { get; set; }
    }
}
