//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryCost
    {
        public int DeliveryCost_ID { get; set; }
        public Nullable<int> DeliveryCollection_ID { get; set; }
    
        public virtual DeliveryCollection DeliveryCollection { get; set; }
    }
}
