//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeSale.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBS_POSableEntities : DbContext
    {
        public DBS_POSableEntities()
            : base("name=DBS_POSableEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Bottle_Colour> C_Bottle_Colour { get; set; }
        public virtual DbSet<C_Employee_Status> C_Employee_Status { get; set; }
        public virtual DbSet<C_Feedback> C_Feedback { get; set; }
        public virtual DbSet<C_Image> C_Image { get; set; }
        public virtual DbSet<C_Label_Colour> C_Label_Colour { get; set; }
        public virtual DbSet<C_Price> C_Price { get; set; }
        public virtual DbSet<C_Product_Size> C_Product_Size { get; set; }
        public virtual DbSet<C_Purpose> C_Purpose { get; set; }
        public virtual DbSet<C_Quotation> C_Quotation { get; set; }
        public virtual DbSet<C_RequestForQuotation> C_RequestForQuotation { get; set; }
        public virtual DbSet<C_RequestForQuotationLinePrice> C_RequestForQuotationLinePrice { get; set; }
        public virtual DbSet<C_Security_Question> C_Security_Question { get; set; }
        public virtual DbSet<C_Shape> C_Shape { get; set; }
        public virtual DbSet<C_Size> C_Size { get; set; }
        public virtual DbSet<C_Supplier_OrderLines> C_Supplier_OrderLines { get; set; }
        public virtual DbSet<C_SupplierOrder> C_SupplierOrder { get; set; }
        public virtual DbSet<C_SupplierOrder_Status> C_SupplierOrder_Status { get; set; }
        public virtual DbSet<C_SupplierOrder_StatusLine> C_SupplierOrder_StatusLine { get; set; }
        public virtual DbSet<C_TrackOrder_Status> C_TrackOrder_Status { get; set; }
        public virtual DbSet<C_User> C_User { get; set; }
        public virtual DbSet<C_UserSecurity_Question> C_UserSecurity_Question { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<CartItem> CartItems { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClientOrder> ClientOrders { get; set; }
        public virtual DbSet<ClientOrderLine> ClientOrderLines { get; set; }
        public virtual DbSet<ClientOrderStatu> ClientOrderStatus { get; set; }
        public virtual DbSet<DeliveryAddress> DeliveryAddresses { get; set; }
        public virtual DbSet<DeliveryCollection> DeliveryCollections { get; set; }
        public virtual DbSet<DeliveryCost> DeliveryCosts { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeStatu> EmployeeStatus { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Flavour> Flavours { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<ProductType> ProductTypes { get; set; }
        public virtual DbSet<ReturnLine> ReturnLines { get; set; }
        public virtual DbSet<ReturnSale> ReturnSales { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<SaleLine> SaleLines { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Surburb> Surburbs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<Measurement> Measurements { get; set; }
    }
}
