//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReturnLine()
        {
            this.ReturnLine1 = new HashSet<ReturnLine>();
        }
    
        public int ReturnLine_ID { get; set; }
        public Nullable<int> SaleLine_ID { get; set; }
        public Nullable<int> ReturnSale_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnLine> ReturnLine1 { get; set; }
        public virtual ReturnLine ReturnLine2 { get; set; }
        public virtual SaleLine SaleLine { get; set; }
    }
}
