//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeSale.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.SaleLines = new HashSet<SaleLine>();
        }
    
        public int Sale_ID { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public System.DateTime SaleDate { get; set; }
        public Nullable<int> Payment_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public string Invoice { get; set; }
        public string ReceiptNumber { get; set; }
        public Nullable<float> Total { get; set; }
        public Nullable<float> SaleVatAmount { get; set; }
        public Nullable<float> BalanceDue { get; set; }
        public Nullable<float> AmountPaid { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Payment Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleLine> SaleLines { get; set; }
    }
}
